import * as THREE from 'https://esm.sh/three@0.161.0';
import {FontLoader} from 'https://esm.sh/three@0.161.0/examples/jsm/loaders/FontLoader.js';
import {OrbitControls} from 'https://esm.sh/three@0.161.0/examples/jsm/controls/OrbitControls.js';
import {STLExporter} from 'https://esm.sh/three@0.161.0/examples/jsm/exporters/STLExporter.js';
import polygonClipping from 'https://esm.sh/polygon-clipping@0.15.7?bundle';

const $=id=>document.getElementById(id); const viewer=$('viewer');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x0b0d11);
const camera=new THREE.PerspectiveCamera(45,1,0.1,5000);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio||1,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; viewer.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.screenSpacePanning=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x30343d,2)); const sun=new THREE.DirectionalLight(0xffffff,2); sun.position.set(120,180,180); scene.add(sun);
const bedLayer=new THREE.Group(),objectLayer=new THREE.Group(); scene.add(bedLayer,objectLayer);
const FONT={helvetiker_regular:'helvetiker_regular.typeface.json',helvetiker_bold:'helvetiker_bold.typeface.json',optimer_regular:'optimer_regular.typeface.json',gentilis_regular:'gentilis_regular.typeface.json'};
const fontCache=new Map(); let font=null,items=[],plates=[],activeBed=0,created=false;
const num=(id,d)=>{const v=Number($(id)?.value);return Number.isFinite(v)?v:d;};
function status(t,c=''){if($('status'))$('status').innerHTML=`<span class="${c}">${t}</span>`;}
function printer(){if($('printer').value==='custom')return{x:Math.max(1,num('cx',200)),y:Math.max(1,num('cy',200)),z:Math.max(1,num('cz',200))};const [x,y,z]=$('printer').value.split(',').map(Number);return{x,y,z};}
function purge(){if($('purgeMode').value==='none')return{x:0,y:0};return{x:Math.max(0,num('purgeX',40)),y:Math.max(0,num('purgeY',40))};}
function bed(){const full=printer(),margin=Math.max(0,num('margin',5)),p=purge();return{full,margin,p,usable:{x:Math.max(1,full.x-margin*2-p.x),y:Math.max(1,full.y-margin*2),z:Math.max(1,full.z-margin*2)}};}
function line(points,color=0x8f98a5,opacity=1){return new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p))),new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity}));}
function label(text,w=170){const c=document.createElement('canvas');c.width=900;c.height=120;const x=c.getContext('2d');x.fillStyle='#dfe4eb';x.font='700 34px Arial';x.textAlign='center';x.fillText(text,450,72);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));s.scale.set(w,22,1);return s;}
function drawBed(){bedLayer.clear();const c=bed(),x=c.full.x,y=c.full.y,g=new THREE.Group();
 const plane=new THREE.Mesh(new THREE.PlaneGeometry(x,y),new THREE.MeshBasicMaterial({color:0x151a21,transparent:true,opacity:.98,side:THREE.DoubleSide}));plane.position.z=-.3;g.add(plane);
 const gs=Math.max(x,y),grid=new THREE.GridHelper(gs,Math.max(10,Math.round(gs/10)),0x4b535f,0x252b34);grid.rotation.x=Math.PI/2;grid.scale.set(x/gs,y/gs,1);grid.position.z=-.08;g.add(grid);
 g.add(line([[-x/2,-y/2,.05],[x/2,-y/2,.05],[x/2,y/2,.05],[-x/2,y/2,.05],[-x/2,-y/2,.05]],0xb7bec8));
 g.add(line([[-x/2,0,.07],[x/2,0,.07]],0x555e6b,.55),line([[0,-y/2,.07],[0,y/2,.07]],0x555e6b,.55));
 const origin=new THREE.Mesh(new THREE.CircleGeometry(2.8,24),new THREE.MeshBasicMaterial({color:0xf5f7fa}));origin.position.set(-x/2,-y/2,.1);g.add(origin);
 const left=-x/2+c.margin+c.p.x,bottom=-y/2+c.margin;const usable=new THREE.Mesh(new THREE.PlaneGeometry(c.usable.x,c.usable.y),new THREE.MeshBasicMaterial({color:0x1d2630,transparent:true,opacity:.48,side:THREE.DoubleSide}));usable.position.set(left+c.usable.x/2,bottom+c.usable.y/2,.01);g.add(usable);
 g.add(line([[left,bottom,.08],[left+c.usable.x,bottom,.08],[left+c.usable.x,bottom+c.usable.y,.08],[left,bottom+c.usable.y,.08],[left,bottom,.08]],0x657180,.9));
 if(c.p.x){const r=new THREE.Mesh(new THREE.PlaneGeometry(c.p.x,c.p.y),new THREE.MeshBasicMaterial({color:0x8b6f35,transparent:true,opacity:.24,side:THREE.DoubleSide}));r.position.set(-x/2+c.margin+c.p.x/2,bottom+c.p.y/2,.03);g.add(r);}
 const l=label(`CAMA ${activeBed+1} · ${x} × ${y} mm`);l.position.set(0,-y*.44,.12);g.add(l);bedLayer.add(g);}
function info(){const c=bed();$('bedInfo').textContent=`Cama total: ${c.full.x} × ${c.full.y} × ${c.full.z} mm · Área útil: ${c.usable.x} × ${c.usable.y} mm · Z útil: ${c.usable.z} mm`;$('purgeInfo').textContent=c.p.x?`Reserva lateral: ${c.p.x} × ${c.p.y} mm.`:'Sin reserva de torre de purga.';$('guideHeight').textContent=`${Math.max(1,num('height',60))} mm`;$('guideDepth').textContent=`${Math.max(.8,num('depth',12))} mm`;$('guideWidth').textContent=num('widthScale',0)>0?`${num('widthScale',0)} mm`:'Natural';}
async function loadFont(){const k=$('fontStyle').value;if(fontCache.has(k)){font=fontCache.get(k);return true;}try{font=await new FontLoader().loadAsync(`https://threejs.org/examples/fonts/${FONT[k]}`);fontCache.set(k,font);return true;}catch(e){console.error(e);status('No se pudo cargar la tipografía.','bad');return false;}}
function poly(shape,seg){const p=shape.extractPoints(seg);return[p.shape.map(v=>[v.x,v.y]),...p.holes.map(r=>r.map(v=>[v.x,v.y]))];}
function boundsPoly(p){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const ring of p)for(const v of ring){minX=Math.min(minX,v[0]);minY=Math.min(minY,v[1]);maxX=Math.max(maxX,v[0]);maxY=Math.max(maxY,v[1]);}return{minX,minY,maxX,maxY,w:maxX-minX,h:maxY-minY};}
function rawChar(ch,size,seg){return font.generateShapes(ch,size).map(s=>poly(s,seg));}
function advance(ch,size){const shapes=font.generateShapes(ch,size);if(!shapes.length)return size*.5;let min=Infinity,max=-Infinity;for(const s of shapes){const b=boundsPoly(poly(s,6));min=Math.min(min,b.minX);max=Math.max(max,b.maxX);}return Math.max(.001,max-min);}
function wordLayout(text,spacing,targetH,targetW){const seg=Math.max(3,num('curveSegments',6));let cursor=0,chars=[];for(const ch of text){const polys=rawChar(ch,1,seg);let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of polys){const b=boundsPoly(p);minX=Math.min(minX,b.minX);minY=Math.min(minY,b.minY);maxX=Math.max(maxX,b.maxX);maxY=Math.max(maxY,b.maxY);}const adv=advance(ch,1);chars.push({ch,polys,x:cursor,minX,minY,maxX,maxY});cursor+=adv+spacing;}
 const naturalW=Math.max(.001,cursor-(chars.length?spacing:0));let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const c of chars){minX=Math.min(minX,c.x+c.minX);maxX=Math.max(maxX,c.x+c.maxX);minY=Math.min(minY,c.minY);maxY=Math.max(maxY,c.maxY);}const naturalH=Math.max(.001,maxY-minY);
 const sy=targetH/naturalH,sx=targetW>0?targetW/naturalW:sy;
 return{chars,naturalW,naturalH,sx,sy,minX,minY,maxX,maxY,width:naturalW*sx,height:naturalH*sy};}
function toScaledPoly(p,c,d){return p.map(r=>r.map(v=>[(v[0]+c.x-data.minX)*data.sx,(v[1]-data.minY)*data.sy]));}
let data=null;
function makeMesh(p,d){if(!p?.[0]||p[0].length<3)return null;const r=p[0],s=new THREE.Shape();s.moveTo(r[0][0],r[0][1]);for(let i=1;i<r.length;i++)s.lineTo(r[i][0],r[i][1]);s.closePath();for(let i=1;i<p.length;i++){const q=p[i];if(q.length<3)continue;const h=new THREE.Path();h.moveTo(q[0][0],q[0][1]);for(let j=1;j<q.length;j++)h.lineTo(q[j][0],q[j][1]);h.closePath();s.holes.push(h);}const z=Math.max(.8,d),be=$('bevel').checked,bs=Math.min(num('bevelSize',1.2),z/2);const g=new THREE.ExtrudeGeometry(s,{depth:z,curveSegments:Math.max(3,num('curveSegments',6)),bevelEnabled:be,bevelSize:bs,bevelThickness:bs,bevelSegments:Math.max(1,num('bevelSegments',2))});g.translate(0,0,-z/2);return new THREE.Mesh(g,new THREE.MeshStandardMaterial({roughness:.65,metalness:.04}));}
function makeWholeWord(layout,d){const g=new THREE.Group();for(const c of layout.chars)for(const p of c.polys){const q=p.map(r=>r.map(v=>[(v[0]+c.x-layout.minX)*layout.sx,(v[1]-layout.minY)*layout.sy]));const m=makeMesh(q,d);if(m)g.add(m);}g.userData={word:true};g.updateMatrixWorld(true);return g;}
function makeCharPiece(layout,c,d){const g=new THREE.Group();for(const p of c.polys){const q=p.map(r=>r.map(v=>[(v[0]+c.x-layout.minX)*layout.sx,(v[1]-layout.minY)*layout.sy]));const m=makeMesh(q,d);if(m)g.add(m);}g.userData={char:c.ch,order:layout.chars.indexOf(c)};g.updateMatrixWorld(true);return g;}
function splitChar(layout,c,d){const cbed=bed(),usableH=cbed.usable.y,usableW=cbed.usable.x;const x0=(c.x+c.minX-layout.minX)*layout.sx,x1=(c.x+c.maxX-layout.minX)*layout.sx,y0=(c.minY-layout.minY)*layout.sy,y1=(c.maxY-layout.minY)*layout.sy;const w=x1-x0,h=y1-y0;
 if(w<=usableW+.001&&h<=usableH+.001)return[makeCharPiece(layout,c,d)];
 const bands=Math.max(1,Math.ceil(h/usableH)),out=[];const polys=c.polys.map(p=>p.map(r=>r.map(v=>[(v[0]+c.x-layout.minX)*layout.sx,(v[1]-layout.minY)*layout.sy])));
 for(let i=0;i<bands;i++){const ya=i*usableH,yb=Math.min(h,(i+1)*usableH),rect=[[[x0-.001,y0+ya-.001],[x1+.001,y0+ya-.001],[x1+.001,y0+yb+.001],[x0-.001,y0+yb+.001],[x0-.001,y0+ya-.001]]],g=new THREE.Group();for(const p of polys){try{for(const cp of polygonClipping.intersection(p,rect))for(const ring of cp){const m=makeMesh([ring],d);if(m)g.add(m);}}catch(e){console.error(e);}}if(g.children.length){g.userData={char:c.ch,order:layout.chars.indexOf(c),split:i};out.push(g);}}
 return out;}
function clearObjects(){items=[];plates=[];objectLayer.clear();$('pieceList').innerHTML='';$('bedList').innerHTML='';created=false;stats();}
function reset(it){it.object.position.set(0,0,0);it.object.rotation.z=0;it.object.updateMatrixWorld(true);}
function box(it,angle=0){reset(it);it.object.rotation.z=angle;it.object.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(it.object);const r={w:b.max.x-b.min.x,h:b.max.y-b.min.y};reset(it);return r;}
function overlap(a,b,g){return a.x<b.x+b.w+g&&a.x+a.w+g>b.x&&a.y<b.y+b.h+g&&a.y+a.h+g>b.y;}
function findSpot(used,w,h,c,g){const candidates=[[0,0]];for(const p of used)candidates.push([p.x+p.w+g,p.y],[p.x,p.y+p.h+g]);let best=null;for(const [x,y] of candidates){if(x<0||y<0||x+w>c.usable.x+.001||y+h>c.usable.y+.001)continue;const r={x,y,w,h};if(used.some(p=>overlap(r,p,g)))continue;const score=(y+h)*100000+x+w;if(!best||score<best.score)best={...r,score};}return best;}
function put(it,r,angle,c){reset(it);it.object.rotation.z=angle;it.object.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(it.object),left=-c.full.x/2+c.margin+c.p.x,bottom=-c.full.y/2+c.margin;it.object.position.x=left+r.x-b.min.x;it.object.position.y=bottom+r.y-b.min.y;it.object.updateMatrixWorld(true);}
function centerPlate(p,c){if(!p.items.length)return;const b=new THREE.Box3();p.items.forEach(it=>b.expandByObject(it.object));const cx=-c.full.x/2+c.margin+c.p.x+c.usable.x/2,cy=-c.full.y/2+c.margin+c.usable.y/2;const dx=cx-(b.min.x+b.max.x)/2,dy=cy-(b.min.y+b.max.y)/2;p.items.forEach(it=>{it.object.position.x+=dx;it.object.position.y+=dy;it.object.updateMatrixWorld(true);});}
function pack(allowRotate=false){const c=bed(),gap=Math.max(0,num('spacing',4));plates=[];activeBed=0;items.forEach(reset);for(const it of items){let placed=false;const angles=allowRotate?[0,Math.PI/2]:[0];for(let pi=0;pi<plates.length&&!placed;pi++){for(const a of angles){const s=box(it,a),r=findSpot(plates[pi].used,s.w,s.h,c,gap);if(r){put(it,r,a,c);plates[pi].items.push(it);plates[pi].used.push(r);it.bed=pi;placed=true;break;}}}if(!placed){const p={items:[],used:[]},s=box(it,0),r=findSpot([],s.w,s.h,c,gap);if(!r){status(`La pieza ${it.id} no entra en la cama útil. Reducí el tamaño.`,'bad');return false;}put(it,r,0,c);p.items.push(it);p.used.push(r);it.bed=plates.length;plates.push(p);}}
 plates.forEach(p=>centerPlate(p,c));drawBed();listBeds();stats();return true;}
function stats(){if(!items.length){$('sx').textContent='—';$('sy').textContent='—';$('sz').textContent='—';$('pieces').textContent='0';return;}const b=new THREE.Box3();items.forEach(it=>b.expandByObject(it.object));$('sx').textContent=(b.max.x-b.min.x).toFixed(1)+' mm';$('sy').textContent=(b.max.y-b.min.y).toFixed(1)+' mm';$('sz').textContent=(b.max.z-b.min.z).toFixed(1)+' mm';$('pieces').textContent=String(items.length);}
function listBeds(){const root=$('bedList');root.innerHTML='';plates.forEach((p,i)=>{const d=document.createElement('div');d.className='bedCard'+(i===activeBed?' active':'');d.innerHTML=`<div class="bedTab"><b>Cama ${i+1}</b><span>${p.items.length} pieza${p.items.length===1?'':'s'}</span></div><button data-bed="${i}">Ver esta cama</button>`;d.querySelector('button').onclick=()=>{activeBed=i;drawBed();listBeds();};root.appendChild(d);});const root2=$('pieceList');root2.innerHTML='';items.forEach(it=>{const d=document.createElement('div');d.className='piece';d.innerHTML=`<b>Pieza ${it.id}</b><span>Cama ${it.bed+1} · ${it.width.toFixed(1)} × ${it.height.toFixed(1)} mm</span>`;root2.appendChild(d);});}
function frame(){const c=bed();camera.position.set(0,0,Math.max(c.full.x,c.full.y)*1.65);camera.up.set(0,1,0);controls.target.set(0,0,0);controls.update();}
function build(){clearObjects();const text=($('text').value||'').trim();if(!text){status('Escribí un texto antes de crear el modelo.','warn');return;}if(!font){status('La tipografía todavía no está lista.','warn');return;}const c=bed(),h=Math.max(1,num('height',60)),d=Math.max(.8,num('depth',12)),sp=Math.max(0,num('spacing',4)),wt=Math.max(0,num('widthScale',0));data=wordLayout(text,sp,h,wt);const whole=makeWholeWord(data,d);const wb=new THREE.Box3().setFromObject(whole);const w=wb.max.x-wb.min.x,hh=wb.max.y-wb.min.y;
 if(w<=c.usable.x+.001&&hh<=c.usable.y+.001){const it={id:1,object:whole,bed:0,width:w,height:hh,source:text};items.push(it);objectLayer.add(whole);pack(false);status(`Texto creado: ${w.toFixed(1)} × ${hh.toFixed(1)} × ${d.toFixed(1)} mm. El texto conserva su orden y queda centrado.`,'ok');}
 else {whole.traverse(o=>{if(o.geometry)o.geometry.dispose();});const parts=[];for(const ch of data.chars)parts.push(...splitChar(data,ch,d));if(!parts.length){status('No se pudo dividir el texto con estas medidas.','bad');return;}parts.forEach((o,i)=>{const b=new THREE.Box3().setFromObject(o);const it={id:i+1,object:o,bed:0,width:b.max.x-b.min.x,height:b.max.y-b.min.y,source:o.userData.char||''};items.push(it);objectLayer.add(o);});if(!pack(false))return;status(`Texto dividido porque supera la cama: ${items.length} pieza${items.length===1?'':'s'}, manteniendo el orden original.`,'ok');}
 created=true;listBeds();stats();}
function centerAll(){if(!items.length){status('Primero creá el modelo.','warn');return;}plates.forEach(p=>centerPlate(p,bed()));drawBed();stats();status('Modelo centrado en la cama. La escala no cambió.','ok');}
function optimize(){if(!items.length){status('Primero creá el modelo.','warn');return;}if(!pack(true))return;status(`Acomodado terminado: ${plates.length} cama${plates.length===1?'':'s'}. La escala física se mantuvo.`,'ok');}
function exportSTL(parts){if(!items.length){status('No hay modelo para exportar.','warn');return;}const ex=new STLExporter();const sceneOut=new THREE.Scene();items.forEach(it=>sceneOut.add(it.object.clone()));const data=ex.parse(sceneOut);const blob=new Blob([data],{type:'model/stl'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=parts?'gemelos3d-piezas.stl':'gemelos3d.stl';a.click();URL.revokeObjectURL(a.href);}
function project(){const payload={app:'Gemelos3D',version:3,text:$('text').value,height:num('height',60),widthTotal:num('widthScale',0),depth:num('depth',12),spacing:num('spacing',4),printer:$('printer').value,margin:num('margin',5),purgeMode:$('purgeMode').value,purgeX:num('purgeX',40),purgeY:num('purgeY',40),font:$('fontStyle').value};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='gemelos3d-proyecto.json';a.click();URL.revokeObjectURL(a.href);}
function wire(){['printer','margin','purgeMode','purgeX','purgeY','cx','cy','cz','height','widthScale','depth','spacing','fontStyle','curveSegments','bevel','bevelSize','bevelSegments'].forEach(id=>$(id)?.addEventListener('change',async()=>{info();if(id==='fontStyle')await loadFont();if(id==='printer'||id==='margin'||id.startsWith('purge')||id.startsWith('c')){drawBed();frame();}}));$('buildTop').onclick=async()=>{if(await loadFont())build();};$('clearText').onclick=clearObjects;$('centerAll').onclick=centerAll;$('optimize').onclick=()=>optimize();$('download').onclick=()=>exportSTL(false);$('downloadPieces').onclick=()=>exportSTL(true);$('project').onclick=project;}
function resize(){const w=Math.max(1,viewer.clientWidth),h=Math.max(1,viewer.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
wire();info();drawBed();frame();resize();window.addEventListener('resize',resize);status('Listo. Escribí el texto arriba y bajá por las opciones.');
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
