import * as THREE from 'https://esm.sh/three@0.161.0';
import {FontLoader} from 'https://esm.sh/three@0.161.0/examples/jsm/loaders/FontLoader.js';
import {OrbitControls} from 'https://esm.sh/three@0.161.0/examples/jsm/controls/OrbitControls.js';
import {STLExporter} from 'https://esm.sh/three@0.161.0/examples/jsm/exporters/STLExporter.js';
import polygonClipping from 'https://esm.sh/polygon-clipping@0.15.7?bundle';
const $=id=>document.getElementById(id),viewer=$('viewer');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b0d11);const camera=new THREE.PerspectiveCamera(45,1,.1,5000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;viewer.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true;scene.add(new THREE.HemisphereLight(0xffffff,0x30343d,2));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(120,180,140);scene.add(sun);const bedLayer=new THREE.Group(),objectLayer=new THREE.Group();scene.add(bedLayer,objectLayer);
const FONT={helvetiker_regular:'helvetiker_regular.typeface.json',helvetiker_bold:'helvetiker_bold.typeface.json',optimer_regular:'optimer_regular.typeface.json',gentilis_regular:'gentilis_regular.typeface.json'};const cache=new Map();let font=null,items=[],plates=[],activeBed=0,created=false;
const n=(id,d)=>{const v=Number($(id)?.value);return Number.isFinite(v)?v:d;};function msg(t,c=''){if($('status'))$('status').innerHTML=`<span class="${c}">${t}</span>`;}
function dims(){if($('printer').value==='custom')return{x:Math.max(1,n('cx',200)),y:Math.max(1,n('cy',200)),z:Math.max(1,n('cz',200))};const [x,y,z]=$('printer').value.split(',').map(Number);return{x,y,z};}function purge(){if($('purgeMode').value==='none')return{x:0,y:0};return{x:Math.max(0,n('purgeX',40)),y:Math.max(0,n('purgeY',40))};}function bed(){const full=dims(),margin=Math.max(0,n('margin',5)),p=purge();return{full,margin,p,usable:{x:Math.max(1,full.x-margin*2-p.x),y:Math.max(1,full.y-margin*2),z:Math.max(1,full.z-margin*2)}};}
function line(ps,color=0x8f98a5,opacity=1){return new THREE.Line(new THREE.BufferGeometry().setFromPoints(ps.map(p=>new THREE.Vector3(...p))),new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity}));}function tag(t,w=170){const c=document.createElement('canvas');c.width=900;c.height=120;const x=c.getContext('2d');x.fillStyle='#dfe4eb';x.font='700 34px Arial';x.textAlign='center';x.fillText(t,450,72);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));s.scale.set(w,22,1);return s;}
function drawBed(){bedLayer.clear();const c=bed(),x=c.full.x,y=c.full.y,g=new THREE.Group();const p=new THREE.Mesh(new THREE.PlaneGeometry(x,y),new THREE.MeshBasicMaterial({color:0x151a21,transparent:true,opacity:.98,side:THREE.DoubleSide}));p.position.z=-.3;g.add(p);const gs=Math.max(x,y),grid=new THREE.GridHelper(gs,Math.max(10,Math.round(gs/10)),0x4b535f,0x252b34);grid.rotation.x=Math.PI/2;grid.scale.set(x/gs,y/gs,1);grid.position.z=-.08;g.add(grid);g.add(line([[-x/2,-y/2,.05],[x/2,-y/2,.05],[x/2,y/2,.05],[-x/2,y/2,.05],[-x/2,-y/2,.05]],0xb7bec8),line([[-x/2,0,.07],[x/2,0,.07]],0x555e6b,.55),line([[0,-y/2,.07],[0,y/2,.07]],0x555e6b,.55));const o=new THREE.Mesh(new THREE.CircleGeometry(2.8,24),new THREE.MeshBasicMaterial({color:0xf5f7fa}));o.position.set(-x/2,-y/2,.1);g.add(o);const left=-x/2+c.margin+c.p.x,bottom=-y/2+c.margin,u=new THREE.Mesh(new THREE.PlaneGeometry(c.usable.x,c.usable.y),new THREE.MeshBasicMaterial({color:0x1d2630,transparent:true,opacity:.48,side:THREE.DoubleSide}));u.position.set(left+c.usable.x/2,bottom+c.usable.y/2,.01);g.add(u);g.add(line([[left,bottom,.08],[left+c.usable.x,bottom,.08],[left+c.usable.x,bottom+c.usable.y,.08],[left,bottom+c.usable.y,.08],[left,bottom,.08]],0x657180,.9));if(c.p.x){const px=-x/2+c.margin+c.p.x/2,r=new THREE.Mesh(new THREE.PlaneGeometry(c.p.x,c.p.y),new THREE.MeshBasicMaterial({color:0x8b6f35,transparent:true,opacity:.24,side:THREE.DoubleSide}));r.position.set(px,bottom+c.p.y/2,.03);g.add(r);}const l=tag(`CAMA ${activeBed+1} · ${x} × ${y} mm`);l.position.set(0,-y*.44,.12);g.add(l);bedLayer.add(g);}
function info(){const c=bed();$('bedInfo').textContent=`Cama total: ${c.full.x} × ${c.full.y} × ${c.full.z} mm · Área útil: ${c.usable.x} × ${c.usable.y} mm · Z útil: ${c.usable.z} mm`;$('purgeInfo').textContent=c.p.x?`Reserva lateral: ${c.p.x} × ${c.p.y} mm.`:'Sin reserva de torre de purga.';$('guideHeight').textContent=`${Math.max(1,n('height',60))} mm`;$('guideDepth').textContent=`${Math.max(.8,n('depth',12))} mm`;$('guideWidth').textContent=n('widthScale',0)>0?`${n('widthScale',0)} mm`:'Natural';}
async function loadFont(){const k=$('fontStyle').value;if(cache.has(k)){font=cache.get(k);return true;}try{font=await new FontLoader().loadAsync(`https://threejs.org/examples/fonts/${FONT[k]}`);cache.set(k,font);return true;}catch(e){console.error(e);msg('No se pudo cargar la tipografía.','bad');return false;}}
function poly(s,seg){const p=s.extractPoints(seg);return[p.shape.map(v=>[v.x,v.y]),...p.holes.map(r=>r.map(v=>[v.x,v.y]))];}function pb(p){let a=Infinity,b=Infinity,c=-Infinity,d=-Infinity;for(const r of p)for(const q of r){a=Math.min(a,q[0]);b=Math.min(b,q[1]);c=Math.max(c,q[0]);d=Math.max(d,q[1]);}return{minX:a,minY:b,maxX:c,maxY:d,w:c-a,h:d-b};}
function geo(p,d){if(!p?.[0]||p[0].length<3)return null;const a=p[0],s=new THREE.Shape();s.moveTo(a[0][0],a[0][1]);for(let i=1;i<a.length;i++)s.lineTo(a[i][0],a[i][1]);s.closePath();for(let h=1;h<p.length;h++){const r=p[h];if(r.length<3)continue;const q=new THREE.Path();q.moveTo(r[0][0],r[0][1]);for(let i=1;i<r.length;i++)q.lineTo(r[i][0],r[i][1]);q.closePath();s.holes.push(q);}const z=Math.max(.8,d),be=$('bevel').checked,bs=Math.min(n('bevelSize',1.2),z/2),g=new THREE.ExtrudeGeometry(s,{depth:z,curveSegments:Math.max(3,n('curveSegments',6)),bevelEnabled:be,bevelSize:bs,bevelThickness:bs,bevelSegments:Math.max(1,n('bevelSegments',2))});g.translate(0,0,-z/2);return g;}
function makeMesh(p,d){const g=geo(p,d);return g?new THREE.Mesh(g,new THREE.MeshStandardMaterial({roughness:.65,metalness:.04})):null;}
function charPolys(ch,h,scale,x,seg){return font.generateShapes(ch,h).map(s=>{const p=poly(s,seg);for(const r of p)for(const q of r){q[0]=q[0]*scale+x;}return p;});}
function makeChar(ch,x,h,d,scale,seg){const g=new THREE.Group();for(const p of charPolys(ch,h,scale,x,seg)){const m=makeMesh(p,d);if(m)g.add(m);}if(!g.children.length)return null;const b=new THREE.Box3().setFromObject(g);g.position.set(-b.min.x,-b.min.y,0);g.userData={char:ch};g.updateMatrixWorld(true);return g;}
function layout(text,h,sp,target){const seg=Math.max(3,n('curveSegments',6)),raw=[];let cursor=0,natural=0;for(const ch of text){let min=Infinity,max=-Infinity;for(const s of font.generateShapes(ch,h)){const b=pb(poly(s,seg));min=Math.min(min,b.minX);max=Math.max(max,b.maxX);}const w=Number.isFinite(min)?Math.max(.001,max-min):h*.35;raw.push({ch,x:cursor});cursor+=w+sp;natural=cursor-sp;}const scale=target>0&&natural>0?target/natural:1;return{raw,scale,gap:sp*scale};}
function reset(it){it.object.position.set(0,0,0);it.object.rotation.z=0;it.object.updateMatrixWorld(true);}function size(it,a=0){reset(it);it.object.rotation.z=a;it.object.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(it.object);const r={w:b.max.x-b.min.x,h:b.max.y-b.min.y};reset(it);return r;}
function overlap(a,b,g){return a.x<b.x+b.w+g&&a.x+a.w+g>b.x&&a.y<b.y+b.h+g&&a.y+a.h+g>b.y;}function spot(used,w,h,c,g){const pts=[[0,0]];for(const p of used)pts.push([p.x+p.w+g,p.y],[p.x,p.y+p.h+g]);let best=null;for(const [x,y] of pts){if(x<0||y<0||x+w>c.usable.x+.001||y+h>c.usable.y+.001)continue;const r={x,y,w,h};if(used.some(p=>overlap(r,p,g)))continue;const score=(y+h)*100000+x+w;if(!best||score<best.score)best={x,y,w,h,score};}return best;}
function place(it,r,a,c){reset(it);it.object.rotation.z=a;it.object.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(it.object),left=-c.full.x/2+c.margin+c.p.x,bottom=-c.full.y/2+c.margin;it.object.position.x=left+r.x-b.min.x;it.object.position.y=bottom+r.y-b.min.y;it.object.updateMatrixWorld(true);}
function center(p,c){if(!p.items.length)return;const b=new THREE.Box3();p.items.forEach(it=>b.expandByObject(it.object));const cx=-c.full.x/2+c.margin+c.p.x+c.usable.x/2,cy=-c.full.y/2+c.margin+c.usable.y/2,dx=cx-(b.min.x+b.max.x)/2,dy=cy-(b.min.y+b.max.y)/2;p.items.forEach(it=>{it.object.position.x+=dx;it.object.position.y+=dy;it.object.updateMatrixWorld(true);});}
function pack(){const c=bed(),gap=Math.max(0,n('spacing',4));plates=[];activeBed=0;items.forEach(reset);for(const it of items){let done=false;for(let pi=0;pi<plates.length&&!done;pi++){const p=plates[pi];for(const a of [0,Math.PI/2]){const s=size(it,a),r=spot(p.used,s.w,s.h,c,gap);if(!r)continue;place(it,r,a,c);p.items.push(it);p.used.push(r);it.bed=pi;done=true;break;}}if(!done){const p={items:[],used:[]},s=size(it,0),r=spot(p.used,s.w,s.h,c,gap);if(!r){msg(`La pieza ${it.id} no entra en la cama útil. Reducí el tamaño.`,'bad');return false;}place(it,r,0,c);p.items.push(it);p.used.push(r);it.bed=plates.length;plates.push(p);}}plates.forEach(p=>center(p,c));lists();stats();return true;}
function build(){clear();const text=($('text').value||'').trim();if(!text){msg('Escribí un texto antes de crear el modelo.','warn');return;}if(!font){msg('La tipografía todavía no está lista.','warn');return;}const c=bed(),h=Math.max(1,n('height',60)),d=Math.max(.8,n('depth',12)),sp=Math.max(0,n('spacing',4)),lay=layout(text,h,sp,n('widthScale',0)),chars=[];for(const it of lay.raw){const g=makeChar(it.ch,it.x*lay.scale,h,d,lay.scale,Math.max(3,n('curveSegments',6)));if(g){g.userData.order=chars.length;chars.push(g);}}if(!chars.length){msg('No se pudo generar el texto.','bad');return;}const final=[];for(const g of chars){const b=new THREE.Box3().setFromObject(g),w=b.max.x-b.min.x,hh=b.max.y-b.min.y;if(w<=c.usable.x+.01&&hh<=c.usable.y+.01){final.push(g);continue;}const ch=g.userData.char,base=charPolys(ch,h,lay.scale,0,Math.max(3,n('curveSegments',6))),bands=Math.ceil(hh/c.usable.y),bh=hh/bands;for(let bi=0;bi<bands;bi++){const y0=bi*bh,y1=Math.min(hh,(bi+1)*bh),band=new THREE.Group();for(const p of base){const q=p.map(r=>r.map(v=>[v[0],v[1]-y0])),rect=[[[0,-.001],[w+.001,-.001],[w+.001,y1-y0+.001],[0,y1-y0+.001],[0,-.001]]];try{for(const cp of polygonClipping.intersection(q,rect)){const m=makeMesh(cp,d);if(m)band.add(m);}}catch(e){console.error(e);}}if(band.children.length){const bb=new THREE.Box3().setFromObject(band);band.position.set(-bb.min.x,-bb.min.y,0);band.userData={char:ch,order:g.userData.order};final.push(band);}}}
items=final.map((o,i)=>({id:i+1,object:o,char:o.userData.char||'',order:i,bed:0}));items.forEach(it=>objectLayer.add(it.object));created=true;if(pack())msg(`Modelo creado: ${items.length} pieza${items.length===1?'':'s'} · texto completo y centrado.`,'ok');fit();}
function clear(){objectLayer.clear();items=[];plates=[];activeBed=0;created=false;$('pieces').textContent='0';$('sx').textContent='—';$('sy').textContent='—';$('sz').textContent='—';$('pieceList').innerHTML='';$('bedList').innerHTML='';drawBed();fit();}
function lists(){const b=$('bedList'),p=$('pieceList');b.innerHTML='';p.innerHTML='';plates.forEach((pl,i)=>{const d=document.createElement('div');d.className=`bedCard ${i===activeBed?'active':''}`;d.innerHTML=`<button class="bedTab" type="button"><b>Cama ${i+1}</b><span>${pl.items.length} pieza${pl.items.length===1?'':'s'}</span></button>`;d.querySelector('button').onclick=()=>{activeBed=i;items.forEach(it=>it.object.visible=it.bed===i);drawBed();lists();fit();};b.appendChild(d);});items.forEach(it=>{const d=document.createElement('div');d.className='piece';d.innerHTML=`<b>Pieza ${it.id}</b><span>${it.char?`“${it.char}” · `:''}Cama ${it.bed+1}</span>`;p.appendChild(d);});items.forEach(it=>it.object.visible=it.bed===activeBed);drawBed();}
function stats(){if(!items.length)return;const b=new THREE.Box3();items.forEach(it=>{if(it.bed===activeBed)b.expandByObject(it.object);});if(b.isEmpty())return;$('sx').textContent=`${(b.max.x-b.min.x).toFixed(1)} mm`;$('sy').textContent=`${(b.max.y-b.min.y).toFixed(1)} mm`;$('sz').textContent=`${Math.max(.8,n('depth',12)).toFixed(1)} mm`;$('pieces').textContent=String(items.length);}
function optimize(){if(!created){msg('Primero creá el modelo y después optimizá las camas.','warn');return;}if(pack()){msg(`Optimizado: ${plates.length} cama${plates.length===1?'':'s'} · sin superposición.`,'ok');fit();}}
function centerAll(){if(!created){msg('Primero creá el modelo.','warn');return;}const c=bed();plates.forEach(p=>center(p,c));lists();fit();msg('Piezas centradas en el área útil.','ok');}
function fit(){const c=bed(),b=new THREE.Box3().setFromObject(bedLayer);if(b.isEmpty())return;const ctr=b.getCenter(new THREE.Vector3()),m=Math.max(c.full.x,c.full.y);camera.position.set(ctr.x,ctr.y+m*.82,m*1.42);controls.target.copy(ctr);camera.near=.1;camera.far=Math.max(5000,m*20);camera.updateProjectionMatrix();}
function resize(){const w=viewer.clientWidth||800,h=viewer.clientHeight||600;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);}
function exportSTL(all=true){if(!created||!items.length){msg('Primero creá el modelo.','warn');return;}const root=new THREE.Group();items.filter(it=>all||it.bed===activeBed).forEach(it=>root.add(it.object.clone(true)));const data=new STLExporter().parse(root,{binary:true}),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'model/stl'}));a.download=all?'gemelos3d-completo.stl':`gemelos3d-cama-${activeBed+1}.stl`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function save(){const data={app:'Gemelos 3D',text:$('text').value,height:n('height',60),width:n('widthScale',0),depth:n('depth',12),spacing:n('spacing',4),printer:$('printer').value,margin:n('margin',5),purgeMode:$('purgeMode').value};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='gemelos3d-proyecto.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function wire(){['printer','margin','purgeMode','purgeX','purgeY','cx','cy','cz','height','widthScale','depth','spacing','fontStyle','curveSegments','bevel','bevelSize','bevelSegments'].forEach(id=>{const e=$(id);if(!e)return;e.addEventListener('input',()=>{info();$('customFields').hidden=$('printer').value!=='custom';$('purgeFields').hidden=$('purgeMode').value==='none';$('bevelFields').hidden=!$('bevel').checked;if(['printer','margin','purgeMode','purgeX','purgeY','cx','cy','cz'].includes(id)){drawBed();fit();}});e.addEventListener('change',()=>{info();if(id==='fontStyle')loadFont();});});$('buildTop').onclick=async()=>{if(await loadFont())build();};$('clearText').onclick=clear;$('optimize').onclick=optimize;$('centerAll').onclick=centerAll;$('download').onclick=()=>exportSTL(true);$('downloadPieces').onclick=()=>exportSTL(false);$('project').onclick=save;}
info();drawBed();wire();resize();fit();window.addEventListener('resize',resize);loadFont();(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera);})();
