import * as THREE from 'https://esm.sh/three@0.161.0';
import {FontLoader} from 'https://esm.sh/three@0.161.0/examples/jsm/loaders/FontLoader.js';
import {TextGeometry} from 'https://esm.sh/three@0.161.0/examples/jsm/geometries/TextGeometry.js';
import {STLExporter} from 'https://esm.sh/three@0.161.0/examples/jsm/exporters/STLExporter.js';
import {OrbitControls} from 'https://esm.sh/three@0.161.0/examples/jsm/controls/OrbitControls.js';

const $=id=>document.getElementById(id),viewer=$('viewer');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101216);
const camera=new THREE.PerspectiveCamera(45,1,.1,5000);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));viewer.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x30343d,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(100,180,120);scene.add(light);
const group=new THREE.Group(),bedsGroup=new THREE.Group();scene.add(group,bedsGroup);
const fontCache=new Map();let font=null,currentObjects=[],beds=[],timer;
const fontBase='https://threejs.org/examples/fonts/';
const fontFiles={helvetiker_regular:'helvetiker_regular.typeface.json',helvetiker_bold:'helvetiker_bold.typeface.json',optimer_regular:'optimer_regular.typeface.json',gentilis_regular:'gentilis_regular.typeface.json'};
function status(m,c=''){const s=$('status');if(s)s.innerHTML=`<span class="${c}">${m}</span>`}
async function ensureFont(){const k=$('fontStyle').value;if(fontCache.has(k)){font=fontCache.get(k);return true}try{status('Cargando tipografía…','warn');font=await new FontLoader().loadAsync(fontBase+(fontFiles[k]||fontFiles.helvetiker_regular));fontCache.set(k,font);return true}catch(e){console.error(e);status('✕ No se pudo cargar la tipografía 3D.','bad');return false}}
function dims(){if($('printer').value==='custom')return{x:+$('cx').value||1,y:+$('cy').value||1,z:+$('cz').value||1};const [x,y,z]=$('printer').value.split(',').map(Number);return{x,y,z}}
function purge(){return $('purgeMode').value==='none'?{x:0,y:0}:{x:Math.max(5,+$('purgeX').value||40),y:Math.max(5,+$('purgeY').value||40)}}
function bedInfo(){const b=dims(),m=Math.max(0,+$('margin').value||0),p=purge();return{...b,margin:m,purge:p,x:Math.max(1,b.x-2*m-p.x),y:Math.max(1,b.y-2*m),z:Math.max(1,b.z-2*m)}}
function updateBedInfo(){const b=dims(),u=bedInfo(),p=purge();$('bedInfo').textContent=`Cama total: ${b.x} × ${b.y} × ${b.z} mm · Área útil: ${u.x} × ${u.y} mm · Z útil: ${u.z} mm`;$('purgeInfo').textContent=p.x?`Reserva lateral: ${p.x} × ${p.y} mm.`:'Sin reserva de torre de purga.'}
function mat(){return new THREE.MeshStandardMaterial({roughness:.65,metalness:.05})}
function makeGeo(ch,h,d){const bevel=$('bevel').checked,bs=Math.min(Math.max(.1,+$('bevelSize').value||1.2),d/2,h/8),bn=Math.max(1,Math.min(6,+$('bevelSegments').value||2)),cs=Math.max(3,+$('curveSegments').value||6);const g=new TextGeometry(ch,{font,size:h,height:d,curveSegments:cs,bevelEnabled:bevel,bevelThickness:bs,bevelSize:bs,bevelSegments:bn});g.computeBoundingBox();return g}
function drawBeds(bed,packed){bedsGroup.clear();const gap=40,off=(packed.length-1)*(bed.x+gap)/2;packed.forEach((b,i)=>{const ox=i*(bed.x+gap)-off;const pts=[[-bed.x/2,-bed.y/2],[bed.x/2,-bed.y/2],[bed.x/2,bed.y/2],[-bed.x/2,bed.y/2],[-bed.x/2,-bed.y/2]].map(([x,y])=>new THREE.Vector3(ox+x,y,0));bedsGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x687383})));const grid=new THREE.GridHelper(Math.max(bed.x,bed.y),Math.max(10,Math.round(Math.max(bed.x,bed.y)/10)),0x333740,0x22262d);grid.rotation.x=Math.PI/2;grid.position.set(ox,0,-.05);bedsGroup.add(grid);if(b.purge.x){const q=new THREE.Mesh(new THREE.BoxGeometry(b.purge.x,b.purge.y,.15),new THREE.MeshBasicMaterial({color:0x333740,transparent:true,opacity:.7}));q.position.set(ox+bed.x/2-bed.margin-b.purge.x/2,-bed.y/2+bed.margin+b.purge.y/2,.1);bedsGroup.add(q)}})}
function packOrdered(objects,bed){const out=[];let cur=null;const next=()=>{cur={items:[],x:bed.margin,y:bed.margin,rowH:0,purge:bed.purge};out.push(cur)};next();for(const o of objects){o.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(o),w=bb.max.x-bb.min.x,h=bb.max.y-bb.min.y;if(w>bed.x+.01||h>bed.y+.01){out[out.length-1].items.push({object:o,invalid:true});continue}if(cur.x+w>bed.margin+bed.x+.01){cur.x=bed.margin;cur.y+=cur.rowH+2;cur.rowH=0}if(cur.y+h>bed.margin+bed.y+.01){next()}const it={object:o,index:objects.indexOf(o),w,h,px:cur.x+w/2-bed.x/2,py:cur.y+h/2-bed.y/2,rot:false,invalid:false};cur.items.push(it);cur.x+=w+2;cur.rowH=Math.max(cur.rowH,h)}return out}
function placeAndCenter(packed,bed){const gap=40,off=(packed.length-1)*(bed.x+gap)/2;packed.forEach((b,bi)=>{const ox=bi*(bed.x+gap)-off;b.items.forEach(it=>{if(it.invalid)return;const o=it.object;o.rotation.z=0;o.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(o),cx=(bb.min.x+bb.max.x)/2,cy=(bb.min.y+bb.max.y)/2;o.position.x+=ox+it.px-cx;o.position.y+=it.py-cy;o.updateMatrixWorld(true)});const valid=b.items.filter(i=>!i.invalid),box=new THREE.Box3();valid.forEach(i=>box.expandByObject(i.object));if(!valid.length)return;const dx=ox-(box.min.x+box.max.x)/2,dy=-(box.min.y+box.max.y)/2;valid.forEach(i=>{i.object.position.x+=dx;i.object.position.y+=dy;i.object.updateMatrixWorld(true)})})}
function fitCamera(b,n){const r=Math.max(b.y,n*b.x+(n-1)*40);camera.position.set(0,r*.72,r*1.55);controls.target.set(0,0,0);controls.minDistance=Math.max(40,r*.42);controls.maxDistance=Math.max(900,r*7);controls.update()}
function updateGuide(w,h,d){$('guideWidth').textContent=w?`${w.toFixed(1)} mm`:'—';$('guideHeight').textContent=`${h.toFixed(1)} mm`;$('guideDepth').textContent=`${d.toFixed(1)} mm`}
async function build(){if(!(await ensureFont()))return;group.clear();currentObjects=[];beds=[];const text=$('text').value||'',h=Math.max(1,+$('height').value||60),d=Math.max(.8,+$('depth').value||12),gap=Math.max(0,+$('spacing').value||4),bed=bedInfo();updateBedInfo();if(!text.trim()){updateGuide(0,h,d);$('sx').textContent='—';$('sy').textContent='—';$('sz').textContent='—';$('pieces').textContent='0';$('bedList').innerHTML='';$('pieceList').innerHTML='';status('Escribí un texto arriba para crear el modelo.','warn');fitCamera(dims(),1);return}let cursor=0,maxH=0;const chars=[];for(const [index,ch] of [...text].entries()){if(ch===' '){cursor+=h*.45+gap;continue}const g=makeGeo(ch,h,d),bb=g.boundingBox,w=bb.max.x-bb.min.x,o=new THREE.Mesh(g,mat());o.position.x=cursor;o.userData={char:ch,index,width:w};chars.push(o);cursor+=w+gap;maxH=Math.max(maxH,bb.max.y-bb.min.y)}const naturalW=Math.max(.001,cursor-gap),target=Math.max(0,+$('widthScale').value||0),scale=target?target/naturalW:1;chars.forEach(o=>{o.position.x*=scale;o.scale.x=scale;o.userData.width*=scale;group.add(o);currentObjects.push(o)});beds=packOrdered(currentObjects,bed);placeAndCenter(beds,bed);drawBeds(dims(),beds);const totalW=target||naturalW,invalid=beds.flatMap(b=>b.items).filter(i=>i.invalid);$('sx').textContent=totalW.toFixed(1);$('sy').textContent=maxH.toFixed(1);$('sz').textContent=d.toFixed(1);$('pieces').textContent=currentObjects.length;updateGuide(totalW,maxH,d);renderLists();fitCamera(dims(),beds.length);status(invalid.length?'✕ Una o más letras no entran en la cama útil. Bajá el ancho total o el alto.':`✓ “${text}” · orden original · conjunto centrado en cama · ${beds.length} cama${beds.length>1?'s':''}.`,invalid.length?'bad':'ok')}
function renderLists(){const p=$('pieceList');p.innerHTML=currentObjects.map((o,i)=>`<div class="piece"><b>Pieza ${i+1}</b><span>${o.userData.char}</span></div>`).join('');const l=$('bedList');l.innerHTML=beds.map((b,i)=>`<div class="bedCard"><b>🛏️ Cama ${i+1}</b><br>${b.items.filter(x=>!x.invalid).length} piezas<button data-bed="${i}" class="exportBed">Exportar STL de esta cama</button></div>`).join('');l.querySelectorAll('.exportBed').forEach(b=>b.onclick=()=>exportBed(+b.dataset.bed))}
function exportObjects(objects,name){const root=new THREE.Group();objects.forEach(o=>root.add(o.clone()));const stl=new STLExporter().parse(root),u=URL.createObjectURL(new Blob([stl],{type:'model/stl'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportBed(i){const os=beds[i]?.items.filter(x=>!x.invalid).map(x=>x.object)||[];if(os.length)exportObjects(os,`gemelos3d-cama-${String(i+1).padStart(2,'0')}.stl`)}
function saveProject(){const data={app:'Gemelos 3D',version:2,text:$('text').value,printer:$('printer').value,margin:$('margin').value,height:$('height').value,widthMm:$('widthScale').value,depth:$('depth').value,spacing:$('spacing').value,font:$('fontStyle').value,curveSegments:$('curveSegments').value,bevel:$('bevel').checked,bevelSize:$('bevelSize').value,bevelSegments:$('bevelSegments').value,purgeMode:$('purgeMode').value,purgeX:$('purgeX').value,purgeY:$('purgeY').value};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='gemelos3d-proyecto.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);status('✓ Proyecto JSON guardado.','ok')}
function schedule(){clearTimeout(timer);timer=setTimeout(build,250)}
$('build').onclick=build;$('buildTop').onclick=build;$('clearText').onclick=()=>{$('text').value='';group.clear();currentObjects=[];beds=[];updateGuide(0,+$('height').value||60,+$('depth').value||12);$('pieces').textContent='0';$('pieceList').innerHTML='';$('bedList').innerHTML='';status('Campo de texto limpio. Escribí algo arriba para crear el modelo.','warn');$('text').focus()};$('project').onclick=saveProject;$('optimize').onclick=()=>status('La optimización automática se ejecuta de forma segura sin alterar el orden del texto.','ok');$('centerAll').onclick=build;$('download').onclick=()=>currentObjects.length&&exportObjects(currentObjects,'gemelos3d-proyecto02.stl');$('downloadPieces').onclick=()=>currentObjects.forEach((o,i)=>exportObjects([o],`gemelos3d-pieza-${String(i+1).padStart(2,'0')}.stl`));
['printer','margin','cx','cy','cz','text','height','widthScale','depth','spacing','curveSegments','bevelSize','bevelSegments','purgeMode','purgeX','purgeY'].forEach(id=>$(id)?.addEventListener('input',()=>{if(id==='printer')$('customFields').hidden=$('printer').value!=='custom';if(id==='purgeMode')$('purgeFields').hidden=$('purgeMode').value==='none';updateBedInfo();if(id==='text')schedule();else schedule()}));$('printer').onchange=build;$('fontStyle').onchange=build;$('bevel').onchange=()=>{ $('bevelFields').hidden=!$('bevel').checked;build()};$('purgeFields').hidden=$('purgeMode').value==='none';$('customFields').hidden=$('printer').value!=='custom';$('bevelFields').hidden=!$('bevel').checked;updateBedInfo();updateGuide(0,60,12);fitCamera(dims(),1);status('Listo. Escribí el texto arriba y tocá “Crear modelo”.','ok');
function resize(){const w=Math.max(1,viewer.clientWidth),h=Math.max(1,viewer.clientHeight||600);renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)})();
