function docValue(id,fallback='—'){const el=document.getElementById(id);return el?(el.value??fallback):fallback;}
function docNum(id,fallback=0){const n=Number(docValue(id,fallback));return Number.isFinite(n)?n:fallback;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pieces(){return [...document.querySelectorAll('#pieceList .piece')].map(row=>{const t=row.textContent.trim();const m=t.match(/Pieza\s+(\d+)\s+Cama\s+(\d+)\s+·\s+([\d.,]+)\s+×\s+([\d.,]+)\s+mm/i);return m?{id:m[1],bed:m[2],w:m[3],h:m[4]}:{id:'—',bed:'—',w:'—',h:'—'};});}
function buildDocument(){
 const ps=pieces(), text=docValue('text','');
 const rows=ps.length?ps.map(p=>`<tr><td>${p.id}</td><td>${p.bed}</td><td>${p.w} mm</td><td>${p.h} mm</td></tr>`).join(''):'<tr><td colspan="4">No hay piezas generadas todavía.</td></tr>';
 return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Gemelos 3D — Documento técnico</title><style>body{font-family:Arial,sans-serif;margin:38px;color:#171717;line-height:1.45}h1{margin-bottom:4px}h2{margin-top:28px;border-bottom:1px solid #ddd;padding-bottom:6px}.meta{color:#666}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 28px}.item{padding:9px 0;border-bottom:1px solid #eee}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{padding:9px;border:1px solid #ddd;text-align:left}th{background:#f5f5f5}.note{padding:12px;background:#f6f6f6;margin-top:20px}@media print{body{margin:18mm}.no-print{display:none}}</style></head><body><h1>Gemelos 3D</h1><div class="meta">Documento técnico de fabricación · ${new Date().toLocaleString('es-AR')}</div><h2>01 · Modelo</h2><div class="grid"><div class="item"><b>Texto</b><br>${esc(text)||'—'}</div><div class="item"><b>Alto</b><br>${docNum('height',60)} mm</div><div class="item"><b>Ancho total</b><br>${docNum('widthScale',0)||'Natural'} ${docNum('widthScale',0)?'mm':''}</div><div class="item"><b>Profundidad</b><br>${docNum('depth',12)} mm</div><div class="item"><b>Separación</b><br>${docNum('spacing',4)} mm</div><div class="item"><b>Tipografía</b><br>${esc(docValue('fontStyle'))}</div></div><h2>02 · Fabricación</h2><div class="grid"><div class="item"><b>Impresora</b><br>${esc(docValue('printer'))}</div><div class="item"><b>Margen</b><br>${docNum('margin',5)} mm</div><div class="item"><b>Camas</b><br>${document.querySelectorAll('#bedList .bedCard').length}</div><div class="item"><b>Piezas</b><br>${ps.length}</div></div><h2>03 · Piezas</h2><table><thead><tr><th>Pieza</th><th>Cama</th><th>Ancho</th><th>Alto</th></tr></thead><tbody>${rows}</tbody></table><div class="note"><b>Nota:</b> este documento describe la configuración y las piezas actualmente generadas. La geometría STL se obtiene directamente del motor de Gemelos 3D; las posiciones finales de cama deben verificarse en la vista de fabricación antes de imprimir.</div><p class="no-print"><button onclick="window.print()">Imprimir / Guardar como PDF</button></p></body></html>`;
}
function installDocs(){
 const aside=document.querySelector('aside');if(!aside||document.getElementById('docsSection'))return;
 const s=document.createElement('section');s.id='docsSection';s.innerHTML=`<h2 class="sectionTitle"><span class="sectionNumber">11</span>📋 Documentación</h2><p class="sectionHint">Generá una ficha técnica lista para revisar, imprimir o guardar como PDF.</p><button id="openTechnicalDoc" class="primary">Abrir documento técnico</button><div class="hint">El documento toma los datos actuales del modelo y de fabricación.</div>`;
 const anchor=document.getElementById('projectSection');anchor?anchor.after(s):aside.appendChild(s);
 s.querySelector('#openTechnicalDoc').onclick=()=>{const w=window.open('about:blank','_blank');if(!w)return;w.document.open();w.document.write(buildDocument());w.document.close();};
}
installDocs();
