import './ui-polish.js';
import './layout-quality-fix.js';
import './cost-ui.js';
import './responsive-workspace.js';
import { TALLER_PLAN_REQUEST, TALLER_PLAN_RESULT, createTallerPlanRequest } from './core/taller-fabrication-events.js';

const viewer = document.getElementById('viewer');
const aside = document.querySelector('aside');
const bedList = document.getElementById('bedList');
const pieceList = document.getElementById('pieceList');

function installFabricationUI(){
  if (!viewer || !aside || !bedList || !pieceList) return;
  if (!document.getElementById('fabricationInspectorStyles')) {
    const style=document.createElement('style'); style.id='fabricationInspectorStyles'; style.textContent=`
      .fabSummary{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:7px 0}.fabSummary div,.fabBedCard,.fabPieceRow,.fabSelected,.fabPlan{padding:7px;border:1px solid #252a33;border-radius:7px;background:#14181f}.fabSummary div{text-align:center}.fabSummary b{display:block;font-size:13px;color:#f5f7fa}.fabSummary span,.fabPlanStatus,.fabBedMain>span,.fabPieceRow span{color:#8d96a3;font-size:9px}.fabSelectedTitle,.fabBedsTitle,.fabPiecesTitle{font-size:9px;letter-spacing:.08em;color:#7f8794;font-weight:800;margin:8px 0 4px}.fabSelected b,.fabSelected span{display:block}.fabSelected span{margin-top:3px;line-height:1.35}.fabBedCard{margin-top:5px;font-size:10px;cursor:pointer}.fabBedCard.active,.fabPieceRow.selected{border-color:#8a95a5;background:#1a1f27}.fabBedMain{display:flex;justify-content:space-between;gap:7px}.fabBedMain>div{min-width:0;flex:1}.fabBedCard button,.fabPlan button{width:100%;margin-top:5px;padding:7px;font-size:9px}.fabPieceRow{display:flex;justify-content:space-between;gap:7px;margin-top:5px;font-size:9px;cursor:pointer}.fabPieceRow b{font-size:10px}.fabPieceRow span{text-align:right}.fabPlan{margin:8px 0;background:#11151b}.fabPlan button{margin-top:0;font-size:10px}.fabPlanStatus{display:block;margin-top:6px;line-height:1.35}.fabPlanDetails{margin-top:7px;display:grid;gap:5px}.fabPlanDetails details{border:1px solid #252a33;border-radius:6px;padding:6px;background:#14181f;font-size:9px}.fabPlanDetails summary{cursor:pointer;font-weight:800}.fabricationPanel:not(.hasBeds) .fabBedsTitle,.fabricationPanel:not(.hasBeds) #fabBeds{display:none}.fabricationPanel:not(.hasPieces) .fabPiecesTitle,.fabricationPanel:not(.hasPieces) #fabPieces{display:none}`; document.head.appendChild(style);
  }
  let panel=document.getElementById('fabricationPanel');
  if(!panel){panel=document.createElement('div');panel.id='fabricationPanel';panel.className='fabricationPanel';panel.innerHTML=`
    <div class="fabHeader"><div><strong>Fabricación</strong><span>Lo que ves acá es lo que se va a fabricar</span></div><span class="fabLive">● EN VIVO</span></div>
    <div class="fabMode" role="tablist" aria-label="Modo de visualización"><button type="button" data-fab-mode="model" class="active">Modelo</button><button type="button" data-fab-mode="fabrication">Fabricación</button></div>
    <div class="fabSummary"><div><b id="fabBedCount">0</b><span>camas</span></div><div><b id="fabPieceCount">0</b><span>piezas</span></div><div><b id="fabActiveBed">—</b><span>cama activa</span></div></div>
    <div class="fabPlan"><button type="button" id="fabPlanButton">Planificar fabricación</button><span class="fabPlanStatus" id="fabPlanStatus" aria-live="polite">Listo para solicitar un plan al Taller.</span><div id="fabPlanDetails" class="fabPlanDetails"></div></div>
    <div class="fabBedsTitle">CAMAS</div><div id="fabBeds"></div><div class="fabSelectedTitle">SELECCIÓN</div><div id="fabSelected" class="fabSelected"><b>Ninguna pieza seleccionada</b><span>Elegí una pieza para ver sus medidas y cama.</span></div><div class="fabPiecesTitle">PIEZAS</div><div id="fabPieces"></div>`;viewer.appendChild(panel);}

  const fabBeds=panel.querySelector('#fabBeds'),fabPieces=panel.querySelector('#fabPieces'),fabSelected=panel.querySelector('#fabSelected'),fabBedCount=panel.querySelector('#fabBedCount'),fabPieceCount=panel.querySelector('#fabPieceCount'),fabActiveBed=panel.querySelector('#fabActiveBed'),fabPlanButton=panel.querySelector('#fabPlanButton'),fabPlanStatus=panel.querySelector('#fabPlanStatus'),fabPlanDetails=panel.querySelector('#fabPlanDetails');
  function readSelected(){const source=document.getElementById('selectedPiece');fabSelected.innerHTML=source?source.innerHTML:'<b>Ninguna pieza seleccionada</b><span>Elegí una pieza para ver sus medidas y cama.</span>';}
  function sync(){const bedCards=[...bedList.querySelectorAll('.bedCard')],pieceRows=[...pieceList.querySelectorAll('.piece')],activeIndex=bedCards.findIndex(card=>card.classList.contains('active'));fabBeds.innerHTML='';bedCards.forEach((card,index)=>{const item=document.createElement('div');item.className=`fabBedCard${index===activeIndex?' active':''}`;const tab=card.querySelector('.bedTab');item.innerHTML=`<div class="fabBedMain"><div>${tab?.innerHTML||`Cama ${index+1}`}</div><span>${index===activeIndex?'ACTIVA':'DISPONIBLE'}</span></div><button type="button">Ver cama ${index+1}</button>`;item.querySelector('button').addEventListener('click',event=>{event.stopPropagation();card.querySelector('button')?.click();});item.addEventListener('click',()=>card.querySelector('button')?.click());fabBeds.appendChild(item);});fabPieces.innerHTML='';pieceRows.forEach(row=>{const item=document.createElement('div');item.className=`fabPieceRow${row.classList.contains('selected')?' selected':''}`;item.innerHTML=row.innerHTML;item.setAttribute('role','button');item.setAttribute('tabindex','0');const activate=()=>row.click();item.addEventListener('click',activate);item.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();activate();}});fabPieces.appendChild(item);});fabBedCount.textContent=String(bedCards.length);fabPieceCount.textContent=String(pieceRows.length);fabActiveBed.textContent=activeIndex>=0?`Cama ${activeIndex+1}`:'—';panel.classList.toggle('hasBeds',bedCards.length>0);panel.classList.toggle('hasPieces',pieceRows.length>0);readSelected();}
  function renderPlan(plan){const summary=plan?.summary||{};fabPlanStatus.textContent=`Plan recibido: ${summary.placed??0} piezas colocadas, ${summary.rejected??0} rechazadas, ${summary.beds??0} camas.`;fabPlanDetails.innerHTML='';(plan?.beds||[]).forEach((bed,index)=>{const details=document.createElement('details');details.open=index===0;const title=document.createElement('summary');title.textContent=`Cama ${index+1} · ${(bed.items||[]).length} piezas`;details.appendChild(title);(bed.items||[]).forEach(item=>{const row=document.createElement('div');row.textContent=`${item.name||item.id} · ${item.width}×${item.depth} mm · ${item.rotation||0}°`;details.appendChild(row);});fabPlanDetails.appendChild(details);});if((plan?.rejected||[]).length){const details=document.createElement('details');const title=document.createElement('summary');title.textContent=`Rechazadas · ${plan.rejected.length}`;details.appendChild(title);plan.rejected.forEach(item=>{const row=document.createElement('div');row.textContent=`${item.name||item.id}: ${item.reason}`;details.appendChild(row);});fabPlanDetails.appendChild(details);}}
  const observer=new MutationObserver(()=>requestAnimationFrame(sync));observer.observe(bedList,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});observer.observe(pieceList,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});sync();
  fabPlanButton?.addEventListener('click',()=>{fabPlanStatus.textContent='Solicitud enviada al Taller. Esperando el plan…';window.dispatchEvent(createTallerPlanRequest());});
  window.addEventListener(TALLER_PLAN_RESULT,event=>renderPlan(event.detail?.plan));
  panel.querySelectorAll('[data-fab-mode]').forEach(btn=>btn.addEventListener('click',()=>{panel.querySelectorAll('[data-fab-mode]').forEach(b=>b.classList.toggle('active',b===btn));const fabrication=btn.dataset.fabMode==='fabrication';viewer.classList.toggle('fabricationMode',fabrication);panel.classList.toggle('fabricationMode',fabrication);if(fabrication){const section=[...aside.querySelectorAll('section')].find(s=>s.querySelector('#bedList'));section?.scrollIntoView({behavior:'smooth',block:'nearest'});}}));
}
installFabricationUI();
